version: 2.1

jobs:
  run-jira-app:
    docker:
      - image: python:3.11-slim
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Jira App
          command: |
            . venv/bin/activate
            python main.py


workflows:
  manual-run:
    jobs:
      - run-jira-app



